plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.js
    spec: "@yarnpkg/plugin-interactive-tools"

yarnPath: .yarn/releases/yarn-berry.js
packageExtensions:
  "mocha@*":
    peerDependencies:
      "esm": "*"
      "ts-node": "*"
      "source-map-support": "*"
    dependencies:
      "esm": "*"
      "ts-node": "*"
      "source-map-support": "*"