branch-defaults:
  master:
    environment: Dailyeats-env
environment-defaults:
  Dailyeats-env:
    branch: master
    repository: aws
global:
  application_name: dailyeats
  branch: null
  default_ec2_keyname: null
  default_platform: Node.js running on 64bit Amazon Linux
  default_region: eu-central-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
