version: 2.1
orbs:
  codecov: codecov/codecov@1.0.2
  node: circleci/node@1.1.6

executors:
  node-postgres:
    docker:
      - image: circleci/node:13.12.0-buster
        environment:
          DB_CONNECTION: pgsql
          DB_NAME: circle_test
          DB_USER: root
          DB_PASS: password
          NODE_ENV: test
          TOKEN_PASSWORD: notsecret
      - image: circleci/postgres:12.2-postgis-ram
        environment:
            POSTGRES_USER: root
            POSTGRES_PASSWORD: password

jobs:
  build-and-test:
    executor:
      name: node-postgres
    steps:
      - checkout
      - run:
          name: Setup Code Climate test-reporter
          command: |
            curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
            chmod +x ./cc-test-reporter
      - run: 
          name: Notify Code Climate before tests
          command:  ./cc-test-reporter before-build
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm test
      - run: 
          name: Upload test result to Code Climate
          command:  ./cc-test-reporter after-build
      - codecov/upload:
          file: coverage/lcov.info
          flags: api
workflows:
    build-and-test:
      jobs:
        - build-and-test